name: jupyanno
channels:
  - damianavila82
  - satra
  - pluraldatum
  - glemaitre
  - conda-forge
  - defaults
  - simpleitk
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas
  - bokeh
  - ipympl
  - SimpleITK
  - scikit-image<=0.20
  - scikit-learn<=0.20
  - nbserverproxy
  - appmode
  - jupyter_dashboards
  - pip:
    - plotly
    - pydicom
    - bs4
    - seaborn==0.7.1
    - cloudpickle
    - fileupload
    - git+https://github.com/chestrays/cornerstone_widget
    - voila
    - voila-material
